### PR TITLE
force flag

### PR DESCRIPTION
**Pull request by bessdsv**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? And you have a merge conflict.

**Comment by bessdsv** [comment]
To build the project, I use the Grunt and one of the stages of the build is run linters to test the code. If linters gave me a message, this is not a reason not to build the project. Messages of linters are recommendations. I Generate the report and see it, fix the error, if possible at the moment. But I should be able to build the project, even with the presence of poor but working code.

**Comment by sindresorhus** [comment]
You can already do that with the `--force` flag. `grunt --force`.

**Comment by etylsarin** [comment]
I don't want to use --force flag for the whole grunt build task but eslint task itself. So the switch would be useful anyway as grunt doesn't support forcing particular tasks from gruntfile, does it?

**Comment by sindresorhus** [comment]
> So the switch would be useful anyway as grunt doesn't support forcing particular tasks from gruntfile, does it?

It doesn't. But where do you think this belongs, manually implemented in every grunt task or in grunt itself? ;)

https://github.com/gruntjs/grunt/issues/new

**Comment by etylsarin** [comment]
I totally agree mate, this should be definitely implemented in the Grunt itself. The trouble is that the issue has been opened almost two years ago and hasn't been resolved since then: https://github.com/gruntjs/grunt/issues/810 
And I would really like to switch from jshint to eslint on our projects but I can't as used linting tool must not break the build process.

**Comment by kokarn** [comment]
I agree with @sindresorhus in principle but the option to don't break on error is something that is really helpful. 

:+1: if it matters

**Comment by rafayepes** [comment]
@sindresorhus will you reconsider adding this option? If there is any issue with previous PR, I'd be happy to try to make a PR that satisfies your requirements. That option is a big deal and while grunt doesn't provide a way to force task, this will help a lot of people. It'll be really sad having to switch to a different grunt task only for that.

Thanks

**Comment by sindresorhus** [comment]
I you don't want grunt-eslint to fail your whole build, just set your ESLint rules to warning instead of error. That's exactly what they're there for.

**Comment by rafayepes** [comment]
Thanks @sindresorhus for your reply. However, I believe this doesn't solve my use case. I want my ESLint rules to throw errors, so in dev environment, developer get errors when they don't follow the rules.

However, I want to be able to use ESLint before deploying, with the same config and see if the code that's going to be deployed follows all the rules as well. However, if for some strange reason some rule fails, I don't want the deploy process to stop because of that.

Hope this make sense. Again, if you are willing to add this functionality, I'll be glad to work in another PR, if the previous one doesn't satisfy you.

Thanks for your time.

**Comment by sindresorhus** [comment]
Found this module for you: https://github.com/floriangosse/grunt-force-task

**Comment by steveoh** [comment]
We skip errors when first starting grunt but have them fail on a watch task. I will try out the linked module. It seems like a useful option when jscs and jshint both have it. It also doesn't add a lot of code.

**Pull request closed without merging**
